version: "3.0"

services:
    web:
      build: 
        context: .
        dockerfile: Dockerfile
      image: harshdalvi976/yuta_app
      ports:
        - "5000:5000"

      depends_on:
        - db
    
    db:

      image: nouchka/sqlite3
      volumes:
        - ./data:/data

      command: ["sqlite3", "/data/app.db"]